export { createEditor } from './editor'
export { buildSchema } from './schema'
export { pos, range } from './pos'
export * from './extensions'
export type {
  AnyCommand,
  AnyDef,
  AttributesSpec,
  AttrSpec,
  Command,
  CommandMap,
  CommandsOf,
  CoreCommands,
  Ctx,
  DecorationSpec,
  DocMark,
  DocNode,
  DomOutput,
  DropData,
  Editor,
  EditorOptions,
  ExtensionDef,
  GlobalAttrSpec,
  InputRule,
  MarkDef,
  NodeDef,
  PasteData,
  NodeViewFactory,
  NodeViewProps,
  NodeViewSpec,
  ParseRule,
  Pos,
  PosMarker,
  Range,
  Selection,
} from './types'
