export { createEditor } from './editor'
export { buildSchema } from './schema'
export * from './extensions'
export type {
  AnyCommand,
  AnyDef,
  AttrSpec,
  Command,
  CommandMap,
  CommandsOf,
  CoreCommands,
  Ctx,
  DocMark,
  DocNode,
  DomOutput,
  Editor,
  EditorOptions,
  ExtensionDef,
  InputRule,
  MarkDef,
  NodeDef,
  NodeViewFactory,
  NodeViewProps,
  NodeViewSpec,
  ParseRule,
  Pos,
  PosMarker,
  Range,
  Selection,
} from './types'
